# Generated by Django 3.2.8 on 2021-11-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('template', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Templates',
            },
        ),
    ]
