# Generated by Django 3.2.8 on 2021-11-04 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(default='', max_length=255)),
                ('short_description', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.TextField(max_length=255)),
                ('parent_id', models.ForeignKey(db_column='parent_id', default=0,
                                                on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=255)),
                ('last_name', models.TextField(max_length=255)),
                ('password', models.TextField(max_length=255)),
                ('phone', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('ip', models.TextField(max_length=255)),
                ('is_registered', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price', models.DecimalField(
                    decimal_places=2, default=0.0, max_digits=13)),
                ('item_name', models.TextField(default='', max_length=255)),
                ('short_description', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('category_id', models.ForeignKey(db_column='category_id', default=0,
                                                  on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.TextField(default='', max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpecProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(max_length=100)),
                ('order_created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('order_finished_at', models.DateTimeField()),
                ('order_updated_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('discount_program', models.IntegerField()),
                ('cust_address', models.TextField(max_length=255)),
                ('cust_phone', models.TextField(max_length=255)),
                ('cust_email', models.TextField(max_length=255)),
                ('order_delivery_at', models.DateTimeField()),
                ('total_sum', models.DecimalField(
                    decimal_places=2, default=0.0, max_digits=13)),
                ('customer_id', models.ForeignKey(db_column='customer_id', default=0,
                                                  on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.customers')),
                ('order_state_id', models.ForeignKey(db_column='order_state_id', default=0,
                                                     on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.orderstates')),
            ],
        ),
        migrations.CreateModel(
            name='OrderContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(db_column='item_id', default=0,
                                              on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.items')),
                ('order_id', models.ForeignKey(db_column='order_id', default=0,
                                               on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.orders')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSpecProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('d_value', models.DateTimeField()),
                ('s_value', models.TextField(max_length=255)),
                ('n_value', models.DecimalField(decimal_places=10, max_digits=23)),
                ('text_value', models.TextField(max_length=255)),
                ('item_id', models.ForeignKey(db_column='item_id', default=0,
                                              on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.items')),
                ('special_property_id', models.ForeignKey(db_column='special_property_id', default=0,
                                                          on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.specproperties')),
            ],
        ),
    ]
