# Generated by Django 3.2.8 on 2021-11-28 21:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Buyer name')),
                ('email', models.CharField(max_length=100, verbose_name='Buyer email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN PROGRESS', 'In Progress'), ('DONE', 'Done')], default='NEW', max_length=15, verbose_name='status')),
                ('total_sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=13, verbose_name='Total sum')),
                ('final_sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=13, verbose_name='Final sum')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13, null=True, verbose_name='Discount')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Create date')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
