# Generated by Django 3.2.8 on 2021-11-24 10:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_itemproperty_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Buyer name')),
                ('email', models.CharField(max_length=100, verbose_name='Buyer email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('promo', models.CharField(max_length=50)),
                ('items', models.ManyToManyField(to='products.Item')),
            ],
        ),
    ]
