# Generated by Django 3.2.8 on 2021-12-16 21:17

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item')),
            ],
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.item')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('status', models.CharField(choices=[('Новый', 'New'), ('В работе', 'In Progress'), ('Завершен', 'Done')], default='Новый', max_length=15)),
                ('total_sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('final_sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=250)),
                ('comment', models.TextField(blank=True, null=True)),
                ('item', models.ManyToManyField(related_name='orders', through='orders.ItemConnections', to='products.Item')),
                ('promocode', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.promocode')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='itemconnections',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
    ]
