# Generated by Django 3.2.8 on 2021-12-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemconnections',
            name='promo_status',
            field=models.BooleanField(default=False),
        ),
    ]
