# Generated by Django 3.2.8 on 2021-12-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='promo_imports')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Импорт из xlsx',
            },
        ),
    ]
