# Generated by Django 3.2.8 on 2021-12-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0002_itemconnections_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemconnections',
            name='image_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemconnections',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='products.item'),
        ),
        migrations.AlterField(
            model_name='itemconnections',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
