# Generated by Django 3.2.8 on 2021-12-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_item_name'),
        ('orders', '0002_promoupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item'),
        ),
    ]
