# Generated by Django 3.2.8 on 2021-12-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_itemconnections_promo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemconnections',
            name='promo_status',
        ),
    ]
