# Generated by Django 3.2.8 on 2021-12-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211213_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemconnections',
            old_name='image_id',
            new_name='image',
        ),
    ]
