# Generated by Django 3.2.8 on 2021-11-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
