# Generated by Django 3.2.8 on 2021-11-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN PROGRESS', 'In Progress'), ('DONE', 'Done')], default='NEW', max_length=15, verbose_name='status'),
        ),
    ]
