// eslint-disable-next-line import/prefer-default-export
export const FETCH_MAINPAGE_START = 'FETCH_MAINPAGE_START';
export const FETCH_MAINPAGE_FAILURE = 'FETCH_MAINPAGE_FAILURE';
export const FETCH_MAINPAGE_SUCCESS = 'FETCH_MAINPAGE_SUCCESS';
export const UPDATE_CART = 'UPDATE_CART';
export const FETCH_CATALOG_START = 'FETCH_CATALOG_START';
export const FETCH_CATALOG_FAILURE = 'FETCH_CATALOG_FAILURE';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
