# Generated by Django 3.2.8 on 2021-11-11 15:46

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(default='', max_length=255)),
                ('short_description', models.TextField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/_work/_projects/netomerch/netomerch-backend/netomerch/media'))),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('item_name', models.TextField(default='', max_length=255)),
                ('short_description', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/_work/_projects/netomerch/netomerch-backend/netomerch/media'))),
                ('category_id', models.ForeignKey(db_column='category_id', default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='SpecProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.TextField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Special property',
                'verbose_name_plural': 'Special Properties',
            },
        ),
        migrations.CreateModel(
            name='ItemSpecProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_value', models.DateTimeField(blank=True, null=True)),
                ('s_value', models.TextField(blank=True, max_length=255, null=True)),
                ('n_value', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('text_value', models.TextField(blank=True, max_length=255, null=True)),
                ('item_id', models.ForeignKey(db_column='item_id', default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.item')),
                ('spec_property_id', models.ForeignKey(db_column='special_property_id', default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.specproperty')),
            ],
            options={
                'verbose_name': "Setting item's special property",
                'verbose_name_plural': "Setting item's special properties",
            },
        ),
        migrations.AddConstraint(
            model_name='itemspecproperty',
            constraint=models.UniqueConstraint(fields=('spec_property_id', 'item_id'), name='unique item_prop'),
        ),
    ]
