# Generated by Django 3.2.8 on 2021-12-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imagecolor',
        ),
        migrations.AddField(
            model_name='item',
            name='imagecolor',
            field=models.ManyToManyField(related_name='itemimagecolor', through='products.ImageColorItem', to='products.DictImageColor'),
        ),
    ]
