# Generated by Django 3.2.8 on 2021-11-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [

    ]
