# Generated by Django 3.2.8 on 2021-11-11 15:48

from django.db import migrations


def insert_default_rows(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    category = apps.get_model("products", "Category")
    category.objects.using(db_alias).bulk_create([
        category(id=0, category_name="root"),
    ])

    item = apps.get_model("products", "Item")
    item.objects.using(db_alias).bulk_create([
        item(id=0, item_name="root"),
    ])

    spec_property = apps.get_model("products", "SpecProperty")
    spec_property.objects.using(db_alias).bulk_create([
        spec_property(id=0, property_name="root"),
    ])


def delete_default_rows(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    spec_property = apps.get_model("products", "SpecProperty")
    spec_property.objects.using(db_alias).filter(id=0).delete()

    item = apps.get_model("products", "Item")
    item.objects.using(db_alias).filter(id=0).delete()

    category = apps.get_model("products", "Category")
    category.objects.using(db_alias).filter(id=0).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_default_rows, delete_default_rows),
    ]
