# Generated by Django 3.2.8 on 2021-11-10 22:38

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211110_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/_work/_projects/netomerch/netomerch-backend/netomerch/media')),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/_work/_projects/netomerch/netomerch-backend/netomerch/media')),
        ),
        migrations.AlterField(
            model_name='item',
            name='short_description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itemspecproperty',
            name='d_value',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemspecproperty',
            name='n_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=23),
        ),
        migrations.AlterField(
            model_name='itemspecproperty',
            name='s_value',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itemspecproperty',
            name='text_value',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='specproperty',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
