# Generated by Django 3.2.8 on 2021-12-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='specialization'),
        ),
    ]
