# Generated by Django 3.2.8 on 2021-11-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211111_0138'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[("INSERT INTO products_category(id, parent_id, category_name, short_description, description, image) VALUES (%s, %s, %s, %s, %s, %s);", [
                  0, 0, 'root', 'root', 'root', ''])],
            reverse_sql=[("DELETE FROM products_category where id=%s;", [0])],
        ),
        migrations.RunSQL(
            sql=[("INSERT INTO products_item(id, category_id, item_name, default_price, short_description, description, image) VALUES (%s, %s, %s, %s, %s, %s, %s);", [
                  0, 0, 'root', 0.00, '', '', ''])],
            reverse_sql=[("DELETE FROM products_item where id=%s;", [0])],
        ),
        migrations.RunSQL(
            sql=[("INSERT INTO products_specproperty(id, property_name, description) VALUES (%s,  %s, %s);", [0, 'root', ''])],
            reverse_sql=[("DELETE FROM products_specproperty where id=%s;", [0])],
        ),
    ]
