# Generated by Django 3.2.8 on 2021-11-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211111_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemspecproperty',
            options={'verbose_name': "Setting item's special property", 'verbose_name_plural': "Setting item's special properties"},
        ),
        migrations.AlterField(
            model_name='itemspecproperty',
            name='d_value',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
