# Generated by Django 3.2.8 on 2021-11-15 17:05

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('products', '0007_add_cats_items_dirs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(default='', max_length=255)),
                ('short_description', models.TextField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categoriesjson')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': "Categories' JSON",
            },
        ),
        migrations.CreateModel(
            name='ItemJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('item_name', models.TextField(default='', max_length=255)),
                ('short_description', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='itemsjson')),
                ('is_published', models.BooleanField(default=False)),
                ('properties', models.JSONField()),
                ('category', models.ManyToManyField(to='products.CategoryJSON')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': "Items' JSON",
            },
        ),
    ]
