# Generated by Django 3.2.8 on 2021-11-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211111_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemspecproperty',
            name='n_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='itemspecproperty',
            name='s_value',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemspecproperty',
            name='text_value',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
