# Generated by Django 3.2.8 on 2021-11-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_categoryjson_itemjson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='itemspecproperty',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='itemspecproperty',
            name='spec_property_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemSpecProperty',
        ),
    ]
