# Generated by Django 3.2.8 on 2021-11-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211111_1301'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemspecproperty',
            constraint=models.UniqueConstraint(fields=('spec_property_id', 'item_id'), name='unique item_prop'),
        ),
    ]
