# Generated by Django 3.2.8 on 2021-11-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_itemproperty_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemProperty',
        ),
    ]
