# Generated by Django 3.2.8 on 2021-11-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211120_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('short_description', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='itemjson',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AlterField(
            model_name='itemjson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item'),
        ),
        migrations.DeleteModel(
            name='CategoryJSON',
        ),
        migrations.AlterField(
            model_name='itemjson',
            name='category',
            field=models.ManyToManyField(to='products.Category'),
        ),
    ]
