# Generated by Django 3.2.8 on 2021-11-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_itemproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_hit',
            field=models.BooleanField(default=False),
        ),
    ]
