# Generated by Django 3.2.8 on 2021-11-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20211120_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('NUMB', 'Number'), ('BOOL', 'Boolean')], default='TEXT', max_length=4, verbose_name='type')),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Item property',
                'verbose_name_plural': 'Item Properties',
            },
        ),
        migrations.DeleteModel(
            name='SpecProperty',
        ),
    ]
