# Generated by Django 3.2.8 on 2021-12-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_item_is_hit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
