# Generated by Django 3.2.8 on 2021-12-10 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20211210_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcolor',
            options={'verbose_name': 'Цвет товара', 'verbose_name_plural': 'Цвета товара'},
        ),
        migrations.AlterField(
            model_name='itemcolorimage',
            name='itemcolor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image', to='products.itemcolor'),
        ),
    ]
