# Generated by Django 3.2.8 on 2021-12-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_itemcolorimage_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemcolor',
            name='images',
            field=models.ManyToManyField(related_name='itemcolor', to='products.Image'),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ItemColorImage',
        ),
    ]
