# Generated by Django 3.2.8 on 2021-12-11 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20211212_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.ManyToManyField(related_name='itemcolor', through='products.ItemColor', to='products.Color'),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemcolorcolor', to='products.color'),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='images',
            field=models.ManyToManyField(to='products.Image'),
        ),
    ]
