# Generated by Django 3.2.8 on 2021-12-12 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20211212_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictImageColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='цвет')),
                ('name_eng', models.CharField(max_length=20, null=True, verbose_name='цвет по-английски')),
                ('image', models.ImageField(upload_to='colors', verbose_name='изображение цвета')),
            ],
            options={
                'verbose_name': 'Классификатор цвета',
                'verbose_name_plural': 'Классификатор цветов',
            },
        ),
        migrations.CreateModel(
            name='ImageColorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item')),
                ('is_main', models.BooleanField(default=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oncolor', to='products.dictimagecolor')),
            ],
            options={
                'verbose_name': 'Изображение цвета товара',
                'verbose_name_plural': 'Изображения цвета товара',
            },
        ),
        migrations.RemoveField(
            model_name='itemcolor',
            name='color',
        ),
        migrations.RemoveField(
            model_name='itemcolor',
            name='images',
        ),
        migrations.RemoveField(
            model_name='itemcolor',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='ItemColor',
        ),
        migrations.AddField(
            model_name='imagecoloritem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onitem', to='products.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ManyToManyField(related_name='itemimagecolor', to='products.ImageColorItem'),
        ),
    ]
