# Generated by Django 3.2.8 on 2021-12-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20211212_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='imagecolor',
        ),
    ]
