# Generated by Django 3.2.8 on 2021-12-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_image_item_imagecolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecoloritem',
            name='is_main',
        ),
        migrations.AddField(
            model_name='imagecoloritem',
            name='is_main_color',
            field=models.BooleanField(default=False, verbose_name='основной цвет'),
        ),
        migrations.AddField(
            model_name='imagecoloritem',
            name='is_main_image',
            field=models.BooleanField(default=False, verbose_name='основная картинка'),
        ),
    ]
