# Generated by Django 3.2.8 on 2021-11-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211123_1224'),
        ('products', '0017_auto_20211125_2258'),
    ]

    operations = [
    ]
