# Generated by Django 3.2.8 on 2021-12-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20211212_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
