# Generated by Django 3.2.8 on 2021-12-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_delete_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Классификатор категории', 'verbose_name_plural': 'Классификатор категорий'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Классификатор размера', 'verbose_name_plural': 'Классификатор размеров'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Классификатор специализации', 'verbose_name_plural': 'Классификатор специализаций'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dictimagecolor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='image',
        ),
        migrations.AddField(
            model_name='dictimagecolor',
            name='color_code',
            field=models.CharField(default='#000000', max_length=7, verbose_name='код цвета'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='specialization',
        ),
        migrations.AddField(
            model_name='item',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item', to='products.specialization'),
        ),
    ]
