# Generated by Django 3.2.8 on 2021-12-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_upload_import_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xlsxupload',
            options={'verbose_name': 'Импорт из xlsx'},
        ),
    ]
