# КАТЕГОРИИ!!!

# получение категорий, могут все вообще смотреть
GET http://localhost:8000/api/v1/categories/
Content-Type: application/json

###

# удаление категории от анонима или обычного юзера, нельзя: 403 Forbidden
DELETE http://localhost:8000/api/v1/categories/3/
Content-Type: application/json
Authorization: Basic user1 user1
###

# удаление категории от админа, можно
DELETE http://localhost:8000/api/v1/categories/3/
Content-Type: application/json
Authorization: Basic james qwerty123

###

# создание категории от анонима, нельзя: 403 Forbidden
POST http://localhost:8000/api/v1/categories/
Content-Type: application/json

{
  "name": "Блокноты",
  "slug": "bloknoti",
  "short_description": "Блокноты",
  "description": "Клёвые блокноты"
}

###

# создание категории от админа, можно
POST http://localhost:8000/api/v1/categories/
Content-Type: application/json
Authorization: Basic james qwerty123

{
  "name": "Блокноты",
  "slug": "bloknoti",
  "short_description": "Блокноты",
  "description": "Клёвые блокноты"
}

###

# изменение категории от анонима или простого юзера, нельзя: 403 Forbidden
PATCH http://localhost:8000/api/v1/categories/4/
Content-Type: application/json

{
  "description": "Поменял вот здесь: очень клёвые блокноты"
}

###

# изменение категории от админа, можно
PATCH http://localhost:8000/api/v1/categories/4/
Content-Type: application/json
Authorization: Basic james qwerty123

{
  "description": "Поменял вот здесь: очень клёвые блокноты"
}

###






# ПРОДУКТЫ

# получение продуктов, могут все вообще смотреть
GET http://localhost:8000/api/v1/products/
Content-Type: application/json

###

# удаление продукта от анонима, нельзя: 403 Forbidden
DELETE http://localhost:8000/api/v1/products/3/
Content-Type: application/json

###

# удаление продукта от админа, можно
DELETE http://localhost:8000/api/v1/products/5/
Content-Type: application/json
Authorization: Basic james qwerty123

###

# создание продукта от анонима, нельзя: 403 Forbidden
POST http://localhost:8000/api/v1/products/
Content-Type: application/json

{
  "name": "Блокнот",
  "short_description": "Блокнот для записи кода",
  "description": "Ваще афигеть какой красивый блокнот, куда вы будете записывать все ваши лекции!",
  "category_id": 4
}

###

# создание продукта от админа, можно
POST http://localhost:8000/api/v1/products/
Content-Type: application/json
Authorization: Basic james qwerty123

{
  "name": "Блокнот",
  "short_description": "Блокнот для записи кода",
  "description": "Ваще афигеть какой красивый блокнот, куда вы будете записывать все ваши лекции!",
  "category_id": 4
}

###

# изменение продукта от анонима, нельзя: 403 Forbidden
PATCH http://localhost:8000/api/v1/products/7/
Content-Type: application/json

{
  "category_id": 2
}

###

# изменение продукта от админа, можно
PATCH http://localhost:8000/api/v1/products/7/
Content-Type: application/json
Authorization: Basic james qwerty123

{
  "category_id": 2
}

###
