# Generated by Django 3.2.8 on 2021-12-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dt_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
