# Generated by Django 3.2.8 on 2021-12-02 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='item',
        ),
        migrations.RemoveField(
            model_name='review',
            name='order',
        ),
        migrations.AddField(
            model_name='review',
            name='orders_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.itemconnections'),
            preserve_default=False,
        ),
    ]
