# Generated by Django 3.2.8 on 2021-12-02 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status'),
        ('reviews', '0002_auto_20211202_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='orders_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.itemconnections'),
        ),
    ]
